PRINT_BANNER_XML = "-0" PRINTBANNER = "PRINT"
ENTER_TO_GAME = 1, ENTERTOGAME = "ENTER IN GAME"
ENTER_TO_SINGLE_PLAYER = 2, ENTERSINGLEPLAYER = "ENTER IN SINGLE PLAYER"
ENTER_TO_SCRIPT_EXECUTOR = 3 ENTERSCRIPTEXECUTOR = "ENTER IN SCRIPT EXECUTOR"
